### ISSUE TITLE
Crash and Inventory Generation Issue

### ISSUE THREAD

**Issue by Nodens99** [ahuyn/anomaly-loot#3]
I fixed a vanilla bug with the game_relations.script by reversing the values in the initial function for the goodwill reset.

function reset_goodwill (faction_2 , faction_1) -- Reset the goodwill for actors of both factions
	if ui_options.get("alife/general/war_goodwill_reset") then
		if ( character_community( db.actor ) == faction_1 or ("actor_" .. faction_1) ) then
			relation_registry.set_community_goodwill( faction_2, AC_ID, 0 )
		elseif ( character_community( db.actor ) == faction_2 or ("actor_" .. faction_2) ) then
			relation_registry.set_community_goodwill( faction_1, AC_ID, 0 )
		end
	end
end

After doing this I experienced this issue.

When first accessing trade with mechanics the lockpicks are 100% condition. After leaving the trade and coming back they switch to the lower value. If you kill the trader after allowing this to happen the game will crash.

! [LUA] SCRIPT RUNTIME ERROR
! [LUA] ...ker/anomaly-1.5.1\gamedata\scripts\pickset_binder.script:34: attempt to perform arithmetic on a nil value
! [SCRIPT ERROR]: ...ker/anomaly-1.5.1\gamedata\scripts\pickset_binder.script:34: attempt to perform arithmetic on a nil value
 
FATAL ERROR
 
[error]Expression    : <no expression>
[error]Function      : CScriptEngine::lua_error
[error]File          : ..\xrServerEntities\script_engine.cpp
[error]Line          : 191
[error]Description   : fatal error
[error]Arguments     : LUA error: ...ker/anomaly-1.5.1\gamedata\scripts\pickset_binder.script:34: attempt to perform arithmetic on a nil value
 

stack trace:

**Comment by ahuyn** [comment]
Patched in latest. Not sure what the connection here is, but I added a nil check

**Comment by Nodens99** [comment]
Right, I have no idea how it would interact with your script. Thanks though, I'll be testing it tonight.

**Comment by Nodens99** [comment]
It is no longer Crashing! Although it still seems like you can buy lockpicks at 100% when first talking to a mechanic. I'
m gonna go ahead and close this though.
