### ISSUE TITLE
EFT Lootpool looks like it works but Items are missing.

### ISSUE THREAD

**Issue by Harald92** [ahuyn/anomaly-loot#6]
I added both EFT loot files and it seems like it works, because sometimes I get one or more items of nothing. That makes sense because there are no files for the EFT items and I could not find another mod which would add these.

Are these files work in progress or am I missing something?

**Comment by ahuyn** [comment]
Are you using the EFT items addon by Maid?

**Comment by Harald92** [comment]
No I do not because I could not find any mod on Moddb or google which provide EFT items listed in you lootbox file, that is why I said "Are these files work in progress or am I missing something?". And even with the name of the mod author I still can not find the mod >.<

**Comment by Harald92** [comment]
Would it be a bother to add a link to the EFT item addon from Maid into the description?
